<style type="text/css">
.container{
  display: flex;
}
.card {
  height: 300px;
}
</style>
<div class="container">
    <?php foreach ($this->getBanner() as $banner): ?>
    <div>
      <img src="<?php echo $this->getBaseUrl().'media'.DS.'brand'.DS.'banner'.DS.$banner->banner; ?>" width="100%">
    </div>
    <div>
      <p>Brand Name: <?php echo $banner->name ?></p>
    </div>
    <div>
      <p>Description: <?php echo $banner->description ?></p>
    </div>
    <?php endforeach ?>
</div>


<style type="text/css">
.banner-image{
  height: 500px;
  width: 100%;
  margin-left: -300px;
  position: relative;
  filter: drop-shadow(8px 8px 10px gray);
  filter: blur(1px);
}

.banner-text{
  width: 100%;
  height: 25%;
  position: absolute;
  top: 209px;
  color: white;
  left: 36px;
}

.card-image {
    height: 175px;
    width: auto;
    margin: auto;
    margin-bottom: 10px;
}

.product-div{
  display:flex;
  margin-top: 1em;
}

.card{
  border: 1px solid gray;
  margin-right: 1em;
}

</style>
<div class="product-div" >
  <?php foreach ($this->getProductsByBrand() as $key => $value): ?>

    <div class="card m-1" style="width: 18rem; padding: 1em;">
      <img class="card-img-top card-image" src="<?php echo Mage::getBaseUrl('media').'catalog/product' . $value->getImage() ?>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><?php echo $value->name ?></h5>
        <p><?php echo $value->getShortDescription() ?></p>
        <p><b>$ <?php echo $value->getPrice() ?></b></p>
        <?php echo $value->getUrlKey(); ?>
      </div>
  </div>
  <?php endforeach ?>
</div> 